baseURL = "https://barcelona-declaration.org"
languageCode = "en-us"
title = "Barcelona Declaration - Working Groups"
contentdir = "content"
theme = "beautifulhugo"
enableRobotsTXT = true

[params]
  selfHosted = true
  favicon = "/favicon.jpg"

[params.author]
    mastodon = "mastodon.social/@BarcelonaDORI"
    bluesky = "barcelonadori.bsky.social"
    linkedin = "barcelona-declaration/"
    youtube = "@BarcelonaDeclaration"
    
[[menu.main]]
    name = "Home - Barcelona Declaration"
    url = "https://barcelona-declaration.org"
    weight = 1

[[menu.main]]
    identifier = "working_groups_overview"  
    name = "Working groups"
    url = "/"
    weight = 2
    
[[menu.main]]
    identifier = "working_groups"  
    name = "Working groups"
    url = "/"
    weight = 3

[[menu.main]]
    name = "Working group 1"
    url = "working_group_1/"
    parent = "working_groups"
    weight = 1
    
[[menu.main]]
    name = "Working group 2"
    url = "working_group_2/"
    parent = "working_groups"
    weight = 2
    
[[menu.main]]
    name = "Working group 3"
    url = "working_group_3/"
    parent = "working_groups"
    weight = 3
    
[[menu.main]]
    name = "Working group 4"
    url = "working_group_4/"
    parent = "working_groups"
    weight = 4
    
[[menu.main]]
    name = "Working group 5"
    url = "working_group_5"
    parent = "working_groups"
    weight = 5
    
[[menu.main]]
    name = "Working group 6"
    url = "working_group_6/"
    parent = "working_groups"
    weight = 6
    
[[menu.main]]
    name = "Working group 7"
    url = "working_group_7/"
    parent = "working_groups"
    weight = 7
    